import * as fixture from './fixture-metadata.json';
import { execute, executeWithAction } from '../src/services/engine.service';
import {
  EventMain,
  ProgramRuleAction,
} from '../src/interfaces/rules-engine.types.js';

/*describe('Given empty parameters passed into rule engine', () => {
  it('should have no errors', () => {
    let results = execute({}, {}, [], [], {});
    expect(results.dataValues.length).toEqual(0);
  });
});*/

const testJson = {
  eventWithValues: {
    id: 'e6uCAGJdBcr',
    event: 'e6uCAGJdBcr',
    eventDate: '2020-09-25',
    dueDate: '2020-09-25',
    program: 'ib6PYHQ5Aa8',
    programStage: 'ZjGk4Xvo5r9',
    orgUnit: 'VN8Jjz61jOE',
    trackedEntityInstance: 'sfIC7KC2OXF',
    status: 'ACTIVE',
    dataValues: [
      {
        dataElement: 'UOc2zNtYCAt',
        value: '33332',
      },
      {
        dataElement: 'ynTZOe2zzPD',
        value: 'Male',
      },
      {
        dataElement: 'jJd1ieyyrrM',
        value: 'Yes',
      },
      {
        dataElement: 'uHUGHCcKAQB',
        value: 'Positive',
      },
      {
        dataElement: 'Wd6shffAm5E',
        value: 'Yes',
      },
      {
        dataElement: 'm68e2mT1f1Y',
        value: 'Yes',
      },
      {
        dataElement: 'ZVV4PtiYh7A',
        value: 'Imported',
      },
    ],
    deleted: 'false',
    enrollment: 'Tf4WlXXTdb5',
    synced: false,
  },
  dataElementsObject: {
    UOc2zNtYCAt: {
      name: 'Re-Index ID',
      id: 'UOc2zNtYCAt',
      shortName: 'Re-Index ID',
      aggregationType: 'SUM',
      displayName: 'Re-Index ID',
      valueType: 'NUMBER',
      optionSetValue: false,
    },
    sw4EAynyI60: {
      name: 'Re-Village of residence',
      id: 'sw4EAynyI60',
      shortName: 'Re-Village of residence',
      aggregationType: 'SUM',
      displayName: 'Re-Village of residence',
      valueType: 'ORGANISATION_UNIT',
      optionSetValue: false,
    },
    IgsZFHZYbVJ: {
      name: 'Re- Date of visit',
      id: 'IgsZFHZYbVJ',
      shortName: 'Re- Date of visit',
      aggregationType: 'SUM',
      displayName: 'Re- Date of visit',
      valueType: 'DATE',
      optionSetValue: false,
    },
    FXFcNI1Oyb0: {
      name: 'Re-ACD Case ID',
      id: 'FXFcNI1Oyb0',
      shortName: 'Re-ACD Case ID',
      aggregationType: 'COUNT',
      displayName: 'Re-ACD Case ID',
      valueType: 'NUMBER',
      optionSetValue: false,
    },
    nKoKDmJN01l: {
      name: 'Re-ACD name',
      id: 'nKoKDmJN01l',
      shortName: 'Re-ACD name',
      aggregationType: 'NONE',
      displayName: 'Re-ACD name',
      valueType: 'TEXT',
      optionSetValue: false,
    },
    d1mXAqnn775: {
      name: 'Re-ACD Age',
      id: 'd1mXAqnn775',
      shortName: 'Re-ACD Age',
      aggregationType: 'NONE',
      displayName: 'Re-ACD Age',
      valueType: 'INTEGER_ZERO_OR_POSITIVE',
      optionSetValue: false,
    },
    ynTZOe2zzPD: {
      name: 'Re-ACD Sex',
      id: 'ynTZOe2zzPD',
      shortName: 'Re-ACD Sex',
      aggregationType: 'NONE',
      displayName: 'Re-ACD Sex',
      valueType: 'TEXT',
      optionSetValue: true,
      optionSet: {
        name: 'Sex',
        id: 'ZnVLoAp2WRb',
        options: [
          { code: 'Male', name: 'Male', id: 'sHZeC3hmKwG', sortOrder: 1 },
          { code: 'Female', name: 'Female', id: 'k9uPFST6kxm', sortOrder: 2 },
        ],
      },
    },
    RXhlMxMPEFI: {
      name: 'Re-Occupation',
      id: 'RXhlMxMPEFI',
      shortName: 'Re-Occupation',
      aggregationType: 'NONE',
      displayName: 'Re-Occupation',
      valueType: 'TEXT',
      optionSetValue: true,
      optionSet: {
        name: 'mCBS Occupation',
        id: 'WHVLpT4CHR8',
        options: [
          {
            code: 'Peasants',
            name: 'Peasants',
            id: 'T18S9XFvhsU',
            sortOrder: 1,
          },
          {
            code: 'Business',
            name: 'Business',
            id: 'DWc7Q0zNJsW',
            sortOrder: 2,
          },
          {
            code: 'Employee',
            name: 'Employee',
            id: 'ghur6sYFlZM',
            sortOrder: 3,
          },
          {
            code: 'Pastoralist',
            name: 'Pastoralist',
            id: 'LB3TR74fTmE',
            sortOrder: 4,
          },
          {
            code: 'Pupil/Student',
            name: 'Pupil/Student',
            id: 'LIeBDW6msbP',
            sortOrder: 5,
          },
          {
            code: 'Unemployed',
            name: 'Unemployed',
            id: 'ujqDrnDfURm',
            sortOrder: 6,
          },
          { code: 'Others', name: 'Others', id: 'dQpHo97tdU0', sortOrder: 7 },
        ],
      },
    },
    rt8o34GLnwn: {
      name: 'Re-Relation with index case',
      id: 'rt8o34GLnwn',
      shortName: 'Re-Relation with index case',
      aggregationType: 'NONE',
      displayName: 'Re-Relation with index case',
      valueType: 'TEXT',
      optionSetValue: false,
    },
    jJd1ieyyrrM: {
      name: 'Re-ACD Tested',
      id: 'jJd1ieyyrrM',
      shortName: 'Re-ACD Tested',
      aggregationType: 'NONE',
      displayName: 'Re-ACD Tested',
      valueType: 'TEXT',
      optionSetValue: true,
      optionSet: {
        name: 'Yes/No',
        id: 'WYVdsz7yuus',
        options: [
          { code: 'Yes', name: 'Yes', id: 'OvWxPYgMpSA', sortOrder: 1 },
          { code: 'No', name: 'No', id: 'xXPM0UG0rsn', sortOrder: 2 },
        ],
      },
    },
    uHUGHCcKAQB: {
      name: 'Re-ACD Test Result',
      id: 'uHUGHCcKAQB',
      shortName: 'Re-ACD Test Result',
      aggregationType: 'NONE',
      displayName: 'Re-ACD Test Result',
      valueType: 'TEXT',
      optionSetValue: true,
      optionSet: {
        name: 'Test Result (Positive/Negative)',
        id: 'aoVRajRJe9U',
        options: [
          {
            code: 'Negative',
            name: 'Negative',
            id: 'u5zfYcJOAhn',
            sortOrder: 1,
          },
          {
            code: 'Positive',
            name: 'Positive',
            id: 'hhCLkio1gZg',
            sortOrder: 2,
          },
        ],
      },
    },
    Wd6shffAm5E: {
      name: 'Re-ACD Fever or History of fever in the past 3 days',
      id: 'Wd6shffAm5E',
      shortName: 'Re-ACD Fever or History of fever in the past 3 ',
      aggregationType: 'NONE',
      displayName: 'Re-ACD Fever or History of fever in the past 3 days',
      valueType: 'TEXT',
      optionSetValue: true,
      optionSet: {
        name: 'Yes/No',
        id: 'WYVdsz7yuus',
        options: [
          { code: 'Yes', name: 'Yes', id: 'OvWxPYgMpSA', sortOrder: 1 },
          { code: 'No', name: 'No', id: 'xXPM0UG0rsn', sortOrder: 2 },
        ],
      },
    },
    m68e2mT1f1Y: {
      name: 'Re-ACD Travel in the past 4 weeks',
      id: 'm68e2mT1f1Y',
      shortName: 'Re-ACD Travel in the past 4 weeks',
      aggregationType: 'NONE',
      displayName: 'Re-ACD Travel in the past 4 weeks',
      valueType: 'TEXT',
      optionSetValue: true,
      optionSet: {
        name: 'Yes/No',
        id: 'WYVdsz7yuus',
        options: [
          { code: 'Yes', name: 'Yes', id: 'OvWxPYgMpSA', sortOrder: 1 },
          { code: 'No', name: 'No', id: 'xXPM0UG0rsn', sortOrder: 2 },
        ],
      },
    },
    Nrmpp5Em3fQ: {
      name: 'Re-ACD Place of travel',
      id: 'Nrmpp5Em3fQ',
      shortName: 'Re-ACD Place of travel',
      aggregationType: 'NONE',
      displayName: 'Re-ACD Place of travel',
      valueType: 'ORGANISATION_UNIT',
      optionSetValue: false,
    },
    VEWB20kDYX3: {
      name: 'Re-ACD Travel Period From',
      id: 'VEWB20kDYX3',
      shortName: 'Re-ACD Travel Period From',
      aggregationType: 'NONE',
      displayName: 'Re-ACD Travel Period From',
      valueType: 'DATE',
      optionSetValue: false,
    },
    UZIHjzdqppz: {
      name: 'Re-ACD Travel Period To',
      id: 'UZIHjzdqppz',
      shortName: 'Re-ACD Travel Period To',
      aggregationType: 'NONE',
      displayName: 'Re-ACD Travel Period To',
      valueType: 'DATE',
      optionSetValue: false,
    },
    ZVV4PtiYh7A: {
      name: 'Re-ACD Case classification',
      id: 'ZVV4PtiYh7A',
      shortName: 'Re-ACD Case classification',
      aggregationType: 'NONE',
      displayName: 'Re-ACD Case classification',
      valueType: 'TEXT',
      optionSetValue: true,
      optionSet: {
        name: 'mCBS Case classification',
        id: 'F9u147kfpdR',
        options: [
          { code: 'Local', name: 'Local', id: 'iLrQEBgX7ni', sortOrder: 1 },
          {
            code: 'Imported',
            name: 'Imported',
            id: 'ZTwy5LOATsz',
            sortOrder: 2,
          },
        ],
      },
    },
    GN8P1YHW5mY: {
      name:
        'Re-If local, current foci classification, follow provided job aids',
      id: 'GN8P1YHW5mY',
      shortName: 'Re-If local, current foci classification',
      aggregationType: 'NONE',
      displayName:
        'Re-If local, current foci classification, follow provided job aids',
      valueType: 'TEXT',
      optionSetValue: true,
      optionSet: {
        name: 'mCBS foci classification',
        id: 'rCMKujau63m',
        options: [
          { code: 'Active', name: 'Active', id: 'EIZaimsLJhr', sortOrder: 1 },
          {
            code: 'Residue non active',
            name: 'Residue non active',
            id: 'OEjo0Y40acm',
            sortOrder: 2,
          },
          { code: 'Cleared', name: 'Cleared', id: 'YvQB0vxLNsc', sortOrder: 3 },
        ],
      },
    },
    SFpdcuZMW6W: {
      name:
        'Re-Any known malaria /Fever Case within the same household/neighborhood in the past 28 days',
      id: 'SFpdcuZMW6W',
      shortName: 'Re-known malaria Fever Case within same household',
      aggregationType: 'NONE',
      displayName:
        'Re-Any known malaria /Fever Case within the same household/neighborhood in the past 28 days',
      valueType: 'TEXT',
      optionSetValue: true,
      optionSet: {
        name: 'Yes/No',
        id: 'WYVdsz7yuus',
        options: [
          { code: 'Yes', name: 'Yes', id: 'OvWxPYgMpSA', sortOrder: 1 },
          { code: 'No', name: 'No', id: 'xXPM0UG0rsn', sortOrder: 2 },
        ],
      },
    },
    MiIDFmt7MYg: {
      name: 'Re-Local case classification',
      id: 'MiIDFmt7MYg',
      shortName: 'Re-Local case classification',
      aggregationType: 'NONE',
      displayName: 'Re-Local case classification',
      valueType: 'TEXT',
      optionSetValue: true,
      optionSet: {
        name: 'mCBS Local case classification ',
        id: 'uRToOtz3mHQ',
        options: [
          {
            code: 'Indigenous',
            name: 'Indigenous',
            id: 'VORTUj2KLC5',
            sortOrder: 1,
          },
          {
            code: 'Introduced',
            name: 'Introduced',
            id: 'N3Z9omb7XXt',
            sortOrder: 2,
          },
        ],
      },
    },
  },
  programRules: [
    {
      id: 'B50S6aoeIoT',
      name: 'Re-ACD Hiding fields if client not tested',
      displayName: 'Re-ACD Hiding fields if client not tested',
      lastUpdated: '2020-09-15T12:36:47.477',
      created: '2020-09-15T12:36:47.477',
      condition: "#{Re-ACD Test} == 'No'",
      programRuleActions: [
        {
          created: '2020-09-15T12:36:47.349',
          lastUpdated: '2020-09-15T12:36:47.349',
          id: 'Dz4VgRQINfy',
          programRuleActionType: 'HIDEFIELD',
          dataElement: {
            name: 'Re-ACD Fever or History of fever in the past 3 days',
            id: 'Wd6shffAm5E',
            shortName: 'Re-ACD Fever or History of fever in the past 3 ',
            aggregationType: 'NONE',
            displayName: 'Re-ACD Fever or History of fever in the past 3 days',
            valueType: 'TEXT',
            optionSetValue: true,
            optionSet: {
              name: 'Yes/No',
              id: 'WYVdsz7yuus',
              options: [
                { code: 'Yes', name: 'Yes', id: 'OvWxPYgMpSA', sortOrder: 1 },
                { code: 'No', name: 'No', id: 'xXPM0UG0rsn', sortOrder: 2 },
              ],
            },
          },
          programRule: { id: 'B50S6aoeIoT' },
        },
        {
          created: '2020-09-15T12:36:47.349',
          lastUpdated: '2020-09-15T12:36:47.349',
          id: 'HIaKwwv8Fri',
          programRuleActionType: 'HIDEFIELD',
          dataElement: {
            name: 'Re-ACD Test Result',
            id: 'uHUGHCcKAQB',
            shortName: 'Re-ACD Test Result',
            aggregationType: 'NONE',
            displayName: 'Re-ACD Test Result',
            valueType: 'TEXT',
            optionSetValue: true,
            optionSet: {
              name: 'Test Result (Positive/Negative)',
              id: 'aoVRajRJe9U',
              options: [
                {
                  code: 'Negative',
                  name: 'Negative',
                  id: 'u5zfYcJOAhn',
                  sortOrder: 1,
                },
                {
                  code: 'Positive',
                  name: 'Positive',
                  id: 'hhCLkio1gZg',
                  sortOrder: 2,
                },
              ],
            },
          },
          programRule: { id: 'B50S6aoeIoT' },
        },
      ],
    },
    {
      id: 'DD1gA7wtxnI',
      name: 'mCBS MCR Hiding fields if the case is imported',
      displayName: 'mCBS MCR Hiding fields if the case is imported',
      lastUpdated: '2020-09-20T08:26:25.905',
      created: '2020-09-20T08:26:25.905',
      condition: "A{Case classification} == 'Imported'",
      programRuleActions: [
        {
          created: '2020-09-20T08:26:25.785',
          lastUpdated: '2020-09-20T08:26:25.785',
          id: 'qLiaxXW18hA',
          programRuleActionType: 'HIDEFIELD',
          trackedEntityAttribute: {
            name: 'If local, current foci classification',
            id: 'nXeOcMvi9Os',
            shortName: 'If local, current foci classification',
            generated: false,
            displayName: 'If local, current foci classification',
            valueType: 'TEXT',
            optionSetValue: true,
            optionSet: {
              code: 'If local, current foci classification',
              name: 'If local, current foci classification',
              id: 'jxNWsxR7RLh',
              options: [
                {
                  code: 'Active',
                  name: 'Active',
                  id: 'bsH8XMq0eXz',
                  sortOrder: 1,
                },
                {
                  code: ' Residue non active',
                  name: ' Residue non active',
                  id: 'jVR6KaitQly',
                  sortOrder: 2,
                },
                {
                  code: 'Cleared',
                  name: 'Cleared',
                  id: 'yhaE0Jzrojf',
                  sortOrder: 3,
                },
              ],
            },
          },
          programRule: { id: 'DD1gA7wtxnI' },
        },
        {
          created: '2020-09-20T08:26:25.785',
          lastUpdated: '2020-09-20T08:26:25.785',
          id: 'n3HIBVJGeBm',
          programRuleActionType: 'HIDEFIELD',
          trackedEntityAttribute: {
            name:
              'Any known malaria /Fever Case within the same household/neighborhood in the past 28 days',
            id: 'R3IQKrwOfH0',
            shortName: 'mCBS Any known malaria',
            generated: false,
            displayName:
              'Any known malaria /Fever Case within the same household/neighborhood in the past 28 days',
            valueType: 'BOOLEAN',
            optionSetValue: false,
          },
          programRule: { id: 'DD1gA7wtxnI' },
        },
        {
          created: '2020-09-20T08:26:25.785',
          lastUpdated: '2020-09-20T08:26:25.785',
          id: 'KYSY9WBTZ6x',
          programRuleActionType: 'HIDEFIELD',
          trackedEntityAttribute: {
            name: 'Local case classification ',
            id: 'uAnFHvxxITx',
            shortName: 'mCBS Local case classification ',
            generated: false,
            displayName: 'Local case classification ',
            valueType: 'TEXT',
            optionSetValue: true,
            optionSet: {
              name: 'mCBS Local case classification ',
              id: 'uRToOtz3mHQ',
              options: [
                {
                  code: 'Indigenous',
                  name: 'Indigenous',
                  id: 'VORTUj2KLC5',
                  sortOrder: 1,
                },
                {
                  code: 'Introduced',
                  name: 'Introduced',
                  id: 'N3Z9omb7XXt',
                  sortOrder: 2,
                },
              ],
            },
          },
          programRule: { id: 'DD1gA7wtxnI' },
        },
      ],
    },
    {
      id: 'IrFmmQnkQVv',
      name: 'Re-ACD Hiding fields if not traveled in the past 4 weeks',
      displayName: 'Re-ACD Hiding fields if not traveled in the past 4 weeks',
      lastUpdated: '2020-09-15T12:39:06.921',
      created: '2020-09-15T12:39:06.921',
      condition: "#{Re-ACD Travel the in the past 4 weeks} == 'No'",
      programRuleActions: [
        {
          created: '2020-09-15T12:39:06.784',
          lastUpdated: '2020-09-15T12:39:06.784',
          id: 'fd7nV6ncvzh',
          programRuleActionType: 'HIDEFIELD',
          dataElement: {
            name: 'Re-ACD Travel Period To',
            id: 'UZIHjzdqppz',
            shortName: 'Re-ACD Travel Period To',
            aggregationType: 'NONE',
            displayName: 'Re-ACD Travel Period To',
            valueType: 'DATE',
            optionSetValue: false,
          },
          programRule: { id: 'IrFmmQnkQVv' },
        },
        {
          created: '2020-09-15T12:39:06.784',
          lastUpdated: '2020-09-15T12:39:06.784',
          id: 'mywHUk5vUlW',
          programRuleActionType: 'HIDEFIELD',
          dataElement: {
            name: 'Re-ACD Place of travel',
            id: 'Nrmpp5Em3fQ',
            shortName: 'Re-ACD Place of travel',
            aggregationType: 'NONE',
            displayName: 'Re-ACD Place of travel',
            valueType: 'ORGANISATION_UNIT',
            optionSetValue: false,
          },
          programRule: { id: 'IrFmmQnkQVv' },
        },
        {
          created: '2020-09-15T12:39:06.784',
          lastUpdated: '2020-09-15T12:39:06.784',
          id: 'gtgHWfCV4UL',
          programRuleActionType: 'HIDEFIELD',
          dataElement: {
            name: 'Re-ACD Travel Period From',
            id: 'VEWB20kDYX3',
            shortName: 'Re-ACD Travel Period From',
            aggregationType: 'NONE',
            displayName: 'Re-ACD Travel Period From',
            valueType: 'DATE',
            optionSetValue: false,
          },
          programRule: { id: 'IrFmmQnkQVv' },
        },
      ],
    },
    {
      id: 'ZSCIPuh0tef',
      name: 'mCBS MCR Hiding fields if not traveled in the past 4 weeks',
      displayName: 'mCBS MCR Hiding fields if not traveled in the past 4 weeks',
      lastUpdated: '2020-09-20T08:23:37.900',
      created: '2020-09-20T08:23:37.900',
      condition: "A{Travel in the past 4 weeks} == 'No'",
      programRuleActions: [
        {
          created: '2020-09-20T08:23:37.750',
          lastUpdated: '2020-09-20T08:23:37.750',
          id: 'ndzRSzHBt6b',
          programRuleActionType: 'HIDEFIELD',
          trackedEntityAttribute: {
            name: 'Travel period (to)',
            id: 'IkX30fXj3cb',
            shortName: 'mCBS Travel period (to)',
            generated: false,
            displayName: 'Travel period (to)',
            valueType: 'DATE',
            optionSetValue: false,
          },
          programRule: { id: 'ZSCIPuh0tef' },
        },
        {
          created: '2020-09-20T08:23:37.750',
          lastUpdated: '2020-09-20T08:23:37.750',
          id: 'Xlm2qpWuCBl',
          programRuleActionType: 'HIDEFIELD',
          trackedEntityAttribute: {
            name: 'Travel period (from)',
            id: 'ac59KOtlVW1',
            shortName: 'mCBS Travel period (from)',
            generated: false,
            displayName: 'Travel period (from)',
            valueType: 'DATE',
            optionSetValue: false,
          },
          programRule: { id: 'ZSCIPuh0tef' },
        },
        {
          created: '2020-09-20T08:23:37.750',
          lastUpdated: '2020-09-20T08:23:37.750',
          id: 'StO0PWWlX6e',
          programRuleActionType: 'HIDEFIELD',
          trackedEntityAttribute: {
            name: 'Place of travel ',
            id: 'DZvnwu3pint',
            shortName: 'mCBS Place of travel ',
            generated: false,
            displayName: 'Place of travel ',
            valueType: 'ORGANISATION_UNIT',
            optionSetValue: false,
          },
          programRule: { id: 'ZSCIPuh0tef' },
        },
      ],
    },
    {
      id: 'bxTCpNFlUaK',
      name: 'Re-ACD Hiding fields if the case is imported',
      displayName: 'Re-ACD Hiding fields if the case is imported',
      lastUpdated: '2020-09-15T12:41:12.288',
      created: '2020-09-15T12:41:12.288',
      condition: "#{Re-ACD Case classification} == 'Imported'",
      programRuleActions: [
        {
          created: '2020-09-15T12:41:12.145',
          lastUpdated: '2020-09-15T12:41:12.145',
          id: 'bqVDe2i03qH',
          programRuleActionType: 'HIDEFIELD',
          dataElement: {
            name:
              'Re-Any known malaria /Fever Case within the same household/neighborhood in the past 28 days',
            id: 'SFpdcuZMW6W',
            shortName: 'Re-known malaria Fever Case within same household',
            aggregationType: 'NONE',
            displayName:
              'Re-Any known malaria /Fever Case within the same household/neighborhood in the past 28 days',
            valueType: 'TEXT',
            optionSetValue: true,
            optionSet: {
              name: 'Yes/No',
              id: 'WYVdsz7yuus',
              options: [
                { code: 'Yes', name: 'Yes', id: 'OvWxPYgMpSA', sortOrder: 1 },
                { code: 'No', name: 'No', id: 'xXPM0UG0rsn', sortOrder: 2 },
              ],
            },
          },
          programRule: { id: 'bxTCpNFlUaK' },
        },
        {
          created: '2020-09-15T12:41:12.145',
          lastUpdated: '2020-09-15T12:41:12.145',
          id: 'bj4gT7p2UYa',
          programRuleActionType: 'HIDEFIELD',
          dataElement: {
            name:
              'Re-If local, current foci classification, follow provided job aids',
            id: 'GN8P1YHW5mY',
            shortName: 'Re-If local, current foci classification',
            aggregationType: 'NONE',
            displayName:
              'Re-If local, current foci classification, follow provided job aids',
            valueType: 'TEXT',
            optionSetValue: true,
            optionSet: {
              name: 'mCBS foci classification',
              id: 'rCMKujau63m',
              options: [
                {
                  code: 'Active',
                  name: 'Active',
                  id: 'EIZaimsLJhr',
                  sortOrder: 1,
                },
                {
                  code: 'Residue non active',
                  name: 'Residue non active',
                  id: 'OEjo0Y40acm',
                  sortOrder: 2,
                },
                {
                  code: 'Cleared',
                  name: 'Cleared',
                  id: 'YvQB0vxLNsc',
                  sortOrder: 3,
                },
              ],
            },
          },
          programRule: { id: 'bxTCpNFlUaK' },
        },
        {
          created: '2020-09-15T12:41:12.145',
          lastUpdated: '2020-09-15T12:41:12.145',
          id: 'UqijHaezChu',
          programRuleActionType: 'HIDEFIELD',
          dataElement: {
            name: 'Re-Local case classification',
            id: 'MiIDFmt7MYg',
            shortName: 'Re-Local case classification',
            aggregationType: 'NONE',
            displayName: 'Re-Local case classification',
            valueType: 'TEXT',
            optionSetValue: true,
            optionSet: {
              name: 'mCBS Local case classification ',
              id: 'uRToOtz3mHQ',
              options: [
                {
                  code: 'Indigenous',
                  name: 'Indigenous',
                  id: 'VORTUj2KLC5',
                  sortOrder: 1,
                },
                {
                  code: 'Introduced',
                  name: 'Introduced',
                  id: 'N3Z9omb7XXt',
                  sortOrder: 2,
                },
              ],
            },
          },
          programRule: { id: 'bxTCpNFlUaK' },
        },
      ],
    },
  ],
  programRuleVariables: [
    {
      lastUpdated: '2020-09-15T12:26:56.350',
      created: '2020-09-15T12:26:56.350',
      name: 'Re-ACD Travel To Date',
      id: 'OXrdn75EX4k',
      displayName: 'Re-ACD Travel To Date',
      programRuleVariableSourceType: 'DATAELEMENT_CURRENT_EVENT',
      dataElement: {
        name: 'Re-ACD Travel Period To',
        id: 'UZIHjzdqppz',
        shortName: 'Re-ACD Travel Period To',
        aggregationType: 'NONE',
        displayName: 'Re-ACD Travel Period To',
        valueType: 'DATE',
        optionSetValue: false,
      },
    },
    {
      lastUpdated: '2020-09-15T12:21:25.267',
      created: '2020-09-15T12:21:25.267',
      name: 'Re-ACD Case classification',
      id: 'XU4WpbTK3us',
      displayName: 'Re-ACD Case classification',
      programRuleVariableSourceType: 'DATAELEMENT_CURRENT_EVENT',
      dataElement: {
        name: 'Re-ACD Case classification',
        id: 'ZVV4PtiYh7A',
        shortName: 'Re-ACD Case classification',
        aggregationType: 'NONE',
        displayName: 'Re-ACD Case classification',
        valueType: 'TEXT',
        optionSetValue: true,
        optionSet: {
          name: 'mCBS Case classification',
          id: 'F9u147kfpdR',
          options: [
            { code: 'Local', name: 'Local', id: 'iLrQEBgX7ni', sortOrder: 1 },
            {
              code: 'Imported',
              name: 'Imported',
              id: 'ZTwy5LOATsz',
              sortOrder: 2,
            },
          ],
        },
      },
    },
    {
      lastUpdated: '2020-09-15T12:24:04.512',
      created: '2020-09-15T12:24:04.512',
      name: 'Re-ACD Travel From date',
      id: 'YWeKgRGRM6w',
      displayName: 'Re-ACD Travel From date',
      programRuleVariableSourceType: 'DATAELEMENT_CURRENT_EVENT',
      dataElement: {
        name: 'Re-ACD Travel Period From',
        id: 'VEWB20kDYX3',
        shortName: 'Re-ACD Travel Period From',
        aggregationType: 'NONE',
        displayName: 'Re-ACD Travel Period From',
        valueType: 'DATE',
        optionSetValue: false,
      },
    },
    {
      lastUpdated: '2020-09-20T08:18:12.171',
      created: '2020-09-20T08:18:12.171',
      name: 'Travel period from',
      id: 'SutMSWis6S5',
      displayName: 'Travel period from',
      programRuleVariableSourceType: 'TEI_ATTRIBUTE',
      trackedEntityAttribute: {
        name: 'Travel period (from)',
        id: 'ac59KOtlVW1',
        shortName: 'mCBS Travel period (from)',
        generated: false,
        displayName: 'Travel period (from)',
        valueType: 'DATE',
        optionSetValue: false,
      },
    },
    {
      lastUpdated: '2020-09-15T12:22:55.678',
      created: '2020-09-15T12:22:55.678',
      name: 'Re-ACD Test',
      id: 'u3lIAKg3JPs',
      displayName: 'Re-ACD Test',
      programRuleVariableSourceType: 'DATAELEMENT_CURRENT_EVENT',
      dataElement: {
        name: 'Re-ACD Tested',
        id: 'jJd1ieyyrrM',
        shortName: 'Re-ACD Tested',
        aggregationType: 'NONE',
        displayName: 'Re-ACD Tested',
        valueType: 'TEXT',
        optionSetValue: true,
        optionSet: {
          name: 'Yes/No',
          id: 'WYVdsz7yuus',
          options: [
            { code: 'Yes', name: 'Yes', id: 'OvWxPYgMpSA', sortOrder: 1 },
            { code: 'No', name: 'No', id: 'xXPM0UG0rsn', sortOrder: 2 },
          ],
        },
      },
    },
    {
      lastUpdated: '2020-09-20T08:18:39.180',
      created: '2020-09-20T08:18:39.180',
      name: 'Travel period to',
      id: 'QdyudGq9jnN',
      displayName: 'Travel period to',
      programRuleVariableSourceType: 'TEI_ATTRIBUTE',
      trackedEntityAttribute: {
        name: 'Travel period (to)',
        id: 'IkX30fXj3cb',
        shortName: 'mCBS Travel period (to)',
        generated: false,
        displayName: 'Travel period (to)',
        valueType: 'DATE',
        optionSetValue: false,
      },
    },
    {
      lastUpdated: '2020-09-15T12:32:50.813',
      created: '2020-09-15T12:32:50.813',
      name: 'Re-ACD Travel the in the past 4 weeks',
      id: 'ATLJBmK2wQ6',
      displayName: 'Re-ACD Travel the in the past 4 weeks',
      programRuleVariableSourceType: 'DATAELEMENT_CURRENT_EVENT',
      dataElement: {
        name: 'Re-ACD Travel in the past 4 weeks',
        id: 'm68e2mT1f1Y',
        shortName: 'Re-ACD Travel in the past 4 weeks',
        aggregationType: 'NONE',
        displayName: 'Re-ACD Travel in the past 4 weeks',
        valueType: 'TEXT',
        optionSetValue: true,
        optionSet: {
          name: 'Yes/No',
          id: 'WYVdsz7yuus',
          options: [
            { code: 'Yes', name: 'Yes', id: 'OvWxPYgMpSA', sortOrder: 1 },
            { code: 'No', name: 'No', id: 'xXPM0UG0rsn', sortOrder: 2 },
          ],
        },
      },
    },
    {
      lastUpdated: '2020-09-20T08:16:45.303',
      created: '2020-09-20T08:16:45.303',
      name: 'Case classification',
      id: 'uugVmLF6Dt8',
      displayName: 'Case classification',
      programRuleVariableSourceType: 'TEI_ATTRIBUTE',
      trackedEntityAttribute: {
        name: 'Case classification ',
        id: 'TzQcMwBOMKM',
        shortName: 'mCBS Case classification',
        generated: false,
        displayName: 'Case classification ',
        valueType: 'TEXT',
        optionSetValue: true,
        optionSet: {
          code: 'Case classification',
          name: 'Case classification',
          id: 'MFRsDTS2Qrm',
          options: [
            { code: 'Local', name: 'Local', id: 'sENTCJfkwQI', sortOrder: 1 },
            {
              code: 'Imported',
              name: 'Imported',
              id: 'ksqneXZmHYn',
              sortOrder: 2,
            },
          ],
        },
      },
    },
    {
      lastUpdated: '2020-09-20T08:19:39.991',
      created: '2020-09-20T08:19:39.991',
      name: 'Travel in the past 4 weeks',
      id: 'cWFHiWAJ0Az',
      displayName: 'Travel in the past 4 weeks',
      programRuleVariableSourceType: 'TEI_ATTRIBUTE',
      trackedEntityAttribute: {
        name: 'Travel in the past 4 weeks',
        id: 'fLtLZi9U9sp',
        shortName: 'mCBS Travel in the past 4 weeks',
        generated: false,
        displayName: 'Travel in the past 4 weeks',
        valueType: 'TEXT',
        optionSetValue: true,
        optionSet: {
          name: 'Yes/No',
          id: 'WYVdsz7yuus',
          options: [
            { code: 'Yes', name: 'Yes', id: 'OvWxPYgMpSA', sortOrder: 1 },
            { code: 'No', name: 'No', id: 'xXPM0UG0rsn', sortOrder: 2 },
          ],
        },
      },
    },
  ],
  programRuleActions: [
    {
      created: '2020-09-15T12:36:47.349',
      lastUpdated: '2020-09-15T12:36:47.349',
      id: 'Dz4VgRQINfy',
      programRuleActionType: 'HIDEFIELD',
      dataElement: {
        name: 'Re-ACD Fever or History of fever in the past 3 days',
        id: 'Wd6shffAm5E',
        shortName: 'Re-ACD Fever or History of fever in the past 3 ',
        aggregationType: 'NONE',
        displayName: 'Re-ACD Fever or History of fever in the past 3 days',
        valueType: 'TEXT',
        optionSetValue: true,
        optionSet: {
          name: 'Yes/No',
          id: 'WYVdsz7yuus',
          options: [
            { code: 'Yes', name: 'Yes', id: 'OvWxPYgMpSA', sortOrder: 1 },
            { code: 'No', name: 'No', id: 'xXPM0UG0rsn', sortOrder: 2 },
          ],
        },
      },
      programRule: { id: 'B50S6aoeIoT' },
    },
    {
      created: '2020-09-15T12:36:47.349',
      lastUpdated: '2020-09-15T12:36:47.349',
      id: 'HIaKwwv8Fri',
      programRuleActionType: 'HIDEFIELD',
      dataElement: {
        name: 'Re-ACD Test Result',
        id: 'uHUGHCcKAQB',
        shortName: 'Re-ACD Test Result',
        aggregationType: 'NONE',
        displayName: 'Re-ACD Test Result',
        valueType: 'TEXT',
        optionSetValue: true,
        optionSet: {
          name: 'Test Result (Positive/Negative)',
          id: 'aoVRajRJe9U',
          options: [
            {
              code: 'Negative',
              name: 'Negative',
              id: 'u5zfYcJOAhn',
              sortOrder: 1,
            },
            {
              code: 'Positive',
              name: 'Positive',
              id: 'hhCLkio1gZg',
              sortOrder: 2,
            },
          ],
        },
      },
      programRule: { id: 'B50S6aoeIoT' },
    },
    {
      created: '2020-09-20T08:26:25.785',
      lastUpdated: '2020-09-20T08:26:25.785',
      id: 'qLiaxXW18hA',
      programRuleActionType: 'HIDEFIELD',
      trackedEntityAttribute: {
        name: 'If local, current foci classification',
        id: 'nXeOcMvi9Os',
        shortName: 'If local, current foci classification',
        generated: false,
        displayName: 'If local, current foci classification',
        valueType: 'TEXT',
        optionSetValue: true,
        optionSet: {
          code: 'If local, current foci classification',
          name: 'If local, current foci classification',
          id: 'jxNWsxR7RLh',
          options: [
            { code: 'Active', name: 'Active', id: 'bsH8XMq0eXz', sortOrder: 1 },
            {
              code: ' Residue non active',
              name: ' Residue non active',
              id: 'jVR6KaitQly',
              sortOrder: 2,
            },
            {
              code: 'Cleared',
              name: 'Cleared',
              id: 'yhaE0Jzrojf',
              sortOrder: 3,
            },
          ],
        },
      },
      programRule: { id: 'DD1gA7wtxnI' },
    },
    {
      created: '2020-09-20T08:26:25.785',
      lastUpdated: '2020-09-20T08:26:25.785',
      id: 'n3HIBVJGeBm',
      programRuleActionType: 'HIDEFIELD',
      trackedEntityAttribute: {
        name:
          'Any known malaria /Fever Case within the same household/neighborhood in the past 28 days',
        id: 'R3IQKrwOfH0',
        shortName: 'mCBS Any known malaria',
        generated: false,
        displayName:
          'Any known malaria /Fever Case within the same household/neighborhood in the past 28 days',
        valueType: 'BOOLEAN',
        optionSetValue: false,
      },
      programRule: { id: 'DD1gA7wtxnI' },
    },
    {
      created: '2020-09-20T08:26:25.785',
      lastUpdated: '2020-09-20T08:26:25.785',
      id: 'KYSY9WBTZ6x',
      programRuleActionType: 'HIDEFIELD',
      trackedEntityAttribute: {
        name: 'Local case classification ',
        id: 'uAnFHvxxITx',
        shortName: 'mCBS Local case classification ',
        generated: false,
        displayName: 'Local case classification ',
        valueType: 'TEXT',
        optionSetValue: true,
        optionSet: {
          name: 'mCBS Local case classification ',
          id: 'uRToOtz3mHQ',
          options: [
            {
              code: 'Indigenous',
              name: 'Indigenous',
              id: 'VORTUj2KLC5',
              sortOrder: 1,
            },
            {
              code: 'Introduced',
              name: 'Introduced',
              id: 'N3Z9omb7XXt',
              sortOrder: 2,
            },
          ],
        },
      },
      programRule: { id: 'DD1gA7wtxnI' },
    },
    {
      created: '2020-09-15T12:39:06.784',
      lastUpdated: '2020-09-15T12:39:06.784',
      id: 'fd7nV6ncvzh',
      programRuleActionType: 'HIDEFIELD',
      dataElement: {
        name: 'Re-ACD Travel Period To',
        id: 'UZIHjzdqppz',
        shortName: 'Re-ACD Travel Period To',
        aggregationType: 'NONE',
        displayName: 'Re-ACD Travel Period To',
        valueType: 'DATE',
        optionSetValue: false,
      },
      programRule: { id: 'IrFmmQnkQVv' },
    },
    {
      created: '2020-09-15T12:39:06.784',
      lastUpdated: '2020-09-15T12:39:06.784',
      id: 'mywHUk5vUlW',
      programRuleActionType: 'HIDEFIELD',
      dataElement: {
        name: 'Re-ACD Place of travel',
        id: 'Nrmpp5Em3fQ',
        shortName: 'Re-ACD Place of travel',
        aggregationType: 'NONE',
        displayName: 'Re-ACD Place of travel',
        valueType: 'ORGANISATION_UNIT',
        optionSetValue: false,
      },
      programRule: { id: 'IrFmmQnkQVv' },
    },
    {
      created: '2020-09-15T12:39:06.784',
      lastUpdated: '2020-09-15T12:39:06.784',
      id: 'gtgHWfCV4UL',
      programRuleActionType: 'HIDEFIELD',
      dataElement: {
        name: 'Re-ACD Travel Period From',
        id: 'VEWB20kDYX3',
        shortName: 'Re-ACD Travel Period From',
        aggregationType: 'NONE',
        displayName: 'Re-ACD Travel Period From',
        valueType: 'DATE',
        optionSetValue: false,
      },
      programRule: { id: 'IrFmmQnkQVv' },
    },
    {
      created: '2020-09-20T08:23:37.750',
      lastUpdated: '2020-09-20T08:23:37.750',
      id: 'ndzRSzHBt6b',
      programRuleActionType: 'HIDEFIELD',
      trackedEntityAttribute: {
        name: 'Travel period (to)',
        id: 'IkX30fXj3cb',
        shortName: 'mCBS Travel period (to)',
        generated: false,
        displayName: 'Travel period (to)',
        valueType: 'DATE',
        optionSetValue: false,
      },
      programRule: { id: 'ZSCIPuh0tef' },
    },
    {
      created: '2020-09-20T08:23:37.750',
      lastUpdated: '2020-09-20T08:23:37.750',
      id: 'Xlm2qpWuCBl',
      programRuleActionType: 'HIDEFIELD',
      trackedEntityAttribute: {
        name: 'Travel period (from)',
        id: 'ac59KOtlVW1',
        shortName: 'mCBS Travel period (from)',
        generated: false,
        displayName: 'Travel period (from)',
        valueType: 'DATE',
        optionSetValue: false,
      },
      programRule: { id: 'ZSCIPuh0tef' },
    },
    {
      created: '2020-09-20T08:23:37.750',
      lastUpdated: '2020-09-20T08:23:37.750',
      id: 'StO0PWWlX6e',
      programRuleActionType: 'HIDEFIELD',
      trackedEntityAttribute: {
        name: 'Place of travel ',
        id: 'DZvnwu3pint',
        shortName: 'mCBS Place of travel ',
        generated: false,
        displayName: 'Place of travel ',
        valueType: 'ORGANISATION_UNIT',
        optionSetValue: false,
      },
      programRule: { id: 'ZSCIPuh0tef' },
    },
    {
      created: '2020-09-15T12:41:12.145',
      lastUpdated: '2020-09-15T12:41:12.145',
      id: 'bqVDe2i03qH',
      programRuleActionType: 'HIDEFIELD',
      dataElement: {
        name:
          'Re-Any known malaria /Fever Case within the same household/neighborhood in the past 28 days',
        id: 'SFpdcuZMW6W',
        shortName: 'Re-known malaria Fever Case within same household',
        aggregationType: 'NONE',
        displayName:
          'Re-Any known malaria /Fever Case within the same household/neighborhood in the past 28 days',
        valueType: 'TEXT',
        optionSetValue: true,
        optionSet: {
          name: 'Yes/No',
          id: 'WYVdsz7yuus',
          options: [
            { code: 'Yes', name: 'Yes', id: 'OvWxPYgMpSA', sortOrder: 1 },
            { code: 'No', name: 'No', id: 'xXPM0UG0rsn', sortOrder: 2 },
          ],
        },
      },
      programRule: { id: 'bxTCpNFlUaK' },
    },
    {
      created: '2020-09-15T12:41:12.145',
      lastUpdated: '2020-09-15T12:41:12.145',
      id: 'bj4gT7p2UYa',
      programRuleActionType: 'HIDEFIELD',
      dataElement: {
        name:
          'Re-If local, current foci classification, follow provided job aids',
        id: 'GN8P1YHW5mY',
        shortName: 'Re-If local, current foci classification',
        aggregationType: 'NONE',
        displayName:
          'Re-If local, current foci classification, follow provided job aids',
        valueType: 'TEXT',
        optionSetValue: true,
        optionSet: {
          name: 'mCBS foci classification',
          id: 'rCMKujau63m',
          options: [
            { code: 'Active', name: 'Active', id: 'EIZaimsLJhr', sortOrder: 1 },
            {
              code: 'Residue non active',
              name: 'Residue non active',
              id: 'OEjo0Y40acm',
              sortOrder: 2,
            },
            {
              code: 'Cleared',
              name: 'Cleared',
              id: 'YvQB0vxLNsc',
              sortOrder: 3,
            },
          ],
        },
      },
      programRule: { id: 'bxTCpNFlUaK' },
    },
    {
      created: '2020-09-15T12:41:12.145',
      lastUpdated: '2020-09-15T12:41:12.145',
      id: 'UqijHaezChu',
      programRuleActionType: 'HIDEFIELD',
      dataElement: {
        name: 'Re-Local case classification',
        id: 'MiIDFmt7MYg',
        shortName: 'Re-Local case classification',
        aggregationType: 'NONE',
        displayName: 'Re-Local case classification',
        valueType: 'TEXT',
        optionSetValue: true,
        optionSet: {
          name: 'mCBS Local case classification ',
          id: 'uRToOtz3mHQ',
          options: [
            {
              code: 'Indigenous',
              name: 'Indigenous',
              id: 'VORTUj2KLC5',
              sortOrder: 1,
            },
            {
              code: 'Introduced',
              name: 'Introduced',
              id: 'N3Z9omb7XXt',
              sortOrder: 2,
            },
          ],
        },
      },
      programRule: { id: 'bxTCpNFlUaK' },
    },
  ],
};

describe('Given parameters passed into rule engine', () => {
  it('should return results', () => {
    const optionSets = {};
    let results: ProgramRuleAction[] = executeWithAction(
      testJson.eventWithValues,
      testJson.dataElementsObject,
      testJson.programRules,
      testJson.programRuleVariables,
      testJson.programRuleActions,
      optionSets
    );

    expect(results.length).toEqual(testJson.programRuleActions.length);
  });
});
